# Parameters used to generate this project with aem-project-archetype

groupId=com.uploadpoc
artifactId=uploadpoc
version=1.0.0-SNAPSHOT
package=com.uploadpoc
appId=uploadpoc
appTitle=Upload POC
aemVersion=6.5.17
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=none
singleCountry=y
includeDispatcherConfig=n
includeCommerce=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
